name: Build APK

on:
  push:
    branches:
      - main  # 在主分支推送时触发
  pull_request:
    branches:
      - main  # 在主分支的 PR 时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取代码

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # 设置 JDK 版本为 11
        with:
          java-version: '11'

      - name: Build APK
        run: ./gradlew assembleRelease  # 执行打包命令，注意这里可以根据需要修改

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2  # 上传 APK 文件
        with:
          name: apk
          path: app/build/outputs/apk/release/*.apk  # 修改为你 APK 的实际路径
